Added modprobe

diff --git a/vboxsign b/vboxsign
--- a/vboxsign
+++ b/vboxsign
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Sign VirtualBox modules
+# Sign and load VirtualBox modules
 
 # Run as root
 [ "`whoami`" = root ] || exec sudo "$0" "$@"
@@ -15,9 +15,10 @@ echo
 
 # Sign modules
 for module in vboxdrv vboxnetflt vboxnetadp vboxpci; do
-  [ "`hexdump -e '"%_p"' $(modinfo -n $module) | tail | grep signature`" ] && echo -e "\e[92mModule $module is already signed. Skipping.\e[0m" || /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./MOK.priv ./MOK.der $(modinfo -n $module)
+  [ "`hexdump -e '"%_p"' $(modinfo -n $module) | tail | grep signature`" ] && echo -e "\e[93mModule $module is already signed. Skipping.\e[0m" || /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./MOK.priv ./MOK.der $(modinfo -n $module)
   printf "$module: "
   echo `hexdump -e '"%_p"' $(modinfo -n $module) | tail | grep signature`
+  modprobe $module && echo -e "\e[92m$module successfully loaded\e[0m" || echo -e "\e[91mFailed to load $module\e[0m"
   done
 
 # (Optional) Shred private key
